version: '3.1'

services:
  app:
    tty: true
    stdin_open: true
    build: ./docker/web
    ports:
      - 8000:8000
    volumes:
      - .:/app
    # links:
    #   - db
  # db:
  #   image: mysql:latest
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_DATABASE: mydb
  #     MYSQL_ROOT_PASSWORD: secret
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - php-db:/var/lib/mysql
  # adminer:
  #   image: adminer
  #   ports:
  #     - 18080:8080
# volumes:
#   php-db:
